export const UPDATE_SCORE = 'UPDATE_SCROE';
export const FETCH_H2h_DATA = 'FETCH_H2h_DATA';
export const UPDATE_FIXTURE_STATS = 'UPDATE_FIXTURE_STATS';
export const UPDATE_EVENTS = 'UPDATE_EVENTS ';
export const UPDATE_FIXTURE_DETAILS = 'UPDATE_FIXTURE_DETAILS';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
