export const MATCH_TYPE = 'MATCH_TYPE';
export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_LEAGUE_MATCHES = 'FETCH_LEAGUE_MATCHES';
export const GET_TIMEZONE_COUNTRY = 'GET_TIMEZONE_COUNTRY';
export const SORT_DATA = 'SORT_DATA';
export const CHANGE_SORT_VALUE = 'CHANGE_SORT_VALUE';
