FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
COPY ./package-lock.json ./
COPY yarn.lock ./
COPY ./*.js ./
COPY ./robots-dev.txt ./robots.txt
RUN npm install
COPY . .
EXPOSE 3002

RUN npm run build
CMD ["npm","start"]